### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by shi-ivam** [wyzlle/spacecraft#18]
Your app is very impressive.
I think I might try to build something like this for my next project.
I had one question tho.
How were you guys able to integrate a terminal & and database?

**Comment by wyzlle** [comment]
Glad, That you like your project. We spin up [pseudoterminals](https://en.wikipedia.org/wiki/Pseudoterminal) for supporting interactive I/O. Here's a nodejs binding you can use in your project: [node-pty](https://github.com/microsoft/node-pty)! Databases are managed by [railway](https://dev.new).

**Comment by shi-ivam** [comment]
Thank you for the help.
Keep building such cool stuff in the future.
